-- NOME DO GERENTE DO DEPARTAMENTO 'A00'
SELECT F.NM_FUNC||' '|| F.NM_SOBRENOME AS NOME_GERENTE
  FROM  DEPTO D INNER JOIN FUNC  F 
  ON D.CD_GERENTE = F.CD_MAT
  WHERE F.CD_DEPTO ='A00';
  
  CREATE OR REPLACE FUNCTION F_GERENTE(pDeptno IN DEPTO.CD_DEPTO%TYPE)RETURN VARCHAR2 
    IS   
    vNomeGerente VARCHAR2(200);
  BEGIN
  SELECT F.NM_FUNC||' '|| F.NM_SOBRENOME AS NOME_GERENTE INTO vNomeGerente
  FROM FUNC F INNER JOIN DEPTO D 
  ON D.CD_GERENTE = F.CD_MAT
  WHERE D.CD_DEPTO = pDeptno;
  RETURN vNomeGerente;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        vNomeGerente:='Departamento sem gerente';
        RETURN vNomeGerente; 
      WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001,SQLERRM(SQLCODE));
  END;
  
  SELECT F_GERENTE ('A00') FROM DUAL;
  
  SELECT CD_DEPTO, NM_DEPTO, F_GERENTE(CD_DEPTO) AS GERENTE FROM DEPTO;
  
  SELECT * FROM PROJ;
  
  SELECT F.NM_FUNC || ' ' || F.NM_SOBRENOME AS NomeResponsavel
      FROM FUNC F INNER JOIN PROJ P ON F.CD_MAT = P.CD_RESP
        WHERE P.CD_PROJ ='MA2100';
        
  CREATE OR REPLACE PROCEDURE P_RESPOSAVEL(PCD_PROJ IN PROJ.CD_PROJ%TYPE, PRESP OUT VARCHAR2)
    IS  
  BEGIN  
  SELECT F.NM_FUNC || ' ' || F.NM_SOBRENOME INTO PRESP
      FROM FUNC F INNER JOIN PROJ P ON F.CD_MAT = P.CD_RESP
        WHERE P.CD_PROJ =PCD_PROJ;
    EXCEPTION 
      WHEN NO_DATA_FOUND THEN
        PRESP := 'Projeto sem funcionario';
      WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001,SQLERRM(SQLCODE));      
  END;
  
  SELECT P_RESPOSAVEL('MA2100') FROM DUAL;
    
DECLARE 
  vNome VARCHAR2(200);
  BEGIN
    P_RESPOSAVEL('MA2100',vNome);
    DBMS_OUTPUT.PUT_LINE(vNome);
  END;
